Create Anonymization integration test
oslomet-arx-as-a-service/AaaS pull request #34
Opened 2019-02-25 11:43 UTC by sonhal

2019-02-25 13:52 UTC, JeremiahUy requested changes
Add test for the values of the response payload

2019-02-25 14:47 UTC, Vartdalen commented on src/test/java/no/oslomet/aaas/controller/AnonymizationIntegrationTest.java
> +}
Gjerne legge til assertions på POST request for at test dataene du sender inn kommer gjennom, samt kommer ut som forventet.

2019-02-26 08:18 UTC, JeremiahUy commented on src/test/java/no/oslomet/aaas/controller/AnonymizationIntegrationTest.java
>      }
tenkte mest på å bruke Assert.equals(expected,actual); med en 
String actual = String.ValueOf(responseEntity.getBody().getAnonymizeResult().getData());
String expected = "*,male,81**".....osv.

2019-02-26 08:19 UTC, JeremiahUy commented on src/test/java/no/oslomet/aaas/controller/AnonymizationIntegrationTest.java
>      }
men å sjekke at det ikke er null er også et sjekk vi må gjøre

2019-02-26 08:19 UTC, JeremiahUy commented on src/test/java/no/oslomet/aaas/controller/AnonymizationIntegrationTest.java
>      }
tenker å approve det her, så legger jeg bare ekstra tester

2019-02-26 08:20 UTC, JeremiahUy approved these changes

2019-02-26 11:23 UTC, merged